language: java
cache:
  directories:
  - "$HOME/.m2"
jdk:
- oraclejdk8
sudo: required
services:
- docker
notifications:
  slack:
    secure: lYCu6qQNEXRLn0I+iYQ7WrqH9YBAqlywbUToGMO1d694pjALScIR6OdAuUpUJi/UZAYTClfltyvOMnplFxoaR8VaWm2czRtbaxVkOfZskOnDCLuHzrIbHQwLMPbbyBMd73H+4a0txnqtOmwmf7F9w2aZ+SgstfL8UywqNXUUbpLu2MDYSmJJ4isnBYhrZm1YSnTm1lAsXR2TJ2KpZpsqc1JZUEJT7vXWWt1lev3My5b85l53S21FKyMVe8Frmo3QgmbQB/Lq6I4hEYERubx/pKgghQxblHfgcHK797Ii7MDrhstJARYiPY0BzLPnYxD9Qd0qCBnaK7mJKZDj5AG6QiOj+tW7WGnfQ15nsZvb9m+VNEmU17Y0+lEPk9A06gg/o86YHFV4qymTMqSggVFtUIZD8yZ9LqyjrxuMB7w+2K/ww5A6lEhMY3v006V3Gg5CoMRmDAoGy4Qp/wIaOC58ltVl71nTXTwipbgRVZxxSrsBVosKOiHz8Flv0Un+9PusI8Qt7IGFR4BMp9vz6onq5xrF8TnWABIxJXtvPwbFmSKjpAd74WTcbBFHZb8vDplNeX/KCJcZT3t+xlz2a381hKbHmKM62iMRimClA98Ah8WCH2m9wNk3sfrSIJY+Vp/cqHKKgwfd5OgUyVo+63bgmM/S6K9CY6AAo0XCMC0+w1Y=
  email:
  - anthony.denecheau@gmail.com
  on_success: always
  on_failure: always
env:
  global:
  - secure: Vkeqe68XBk9QwBPuhALxG8/CwNgW3Qgvg1coMpykVA0eUSSdNgaNPV1HR4GFeThQCtfFekH0c8D/kjyNvOhbAy01iCyhgTfIqb3ph05CYkECLX5Kqz9pjsExPqGsSuTFv60rDhQkzPzxqVODS7l7qmt5c2BV8ZMiaGeLUmExV0gZq1cfwQSQsaBtVPMAe5ms6jz8/yNUNhrEruIPdZ/pYYCvheZGGVk+WIkVlnEytVJbEz++WGaWdNjOuul2tNwUf+hUN4hH+PcZkPwfp3YNVzfNxsb0MpKFLY0U2hHXT3ZV8DiO5ZcDqzk5Epoid9L7tL9i3c17qJvfkESTFm6pmvENLbvvQqQalQwDJbyh0Va/r/h1t+NpycvqCfqyayGt/4B1yGRoA5HKz8z09HjZ8I3W8/cIVNc0ptQGzYtM9xAXCNP+iE+XJywdSsRQaa6zU7LXv++puuspUWMkEFK+DcpAc5S5pfCPXpXKo+/HZpcsXCnq4SeF1p1TXkCwiXIaU6SnXswR4uplY4RFrw3EMZLtNyB3IFKN+AXDgvy+DhbqcWqVD/xofQDoaLyXNZK9APoeISsFXhJNtwezq95pTvJQgsiTk0Bgxm/DQE9xwEebG6PNV7N4Do1reZxT8KGLEtzKlfc88ETipJSz3OoAttKEowDzGJsLfcDyl5hDKk0=
  - secure: 299jKD7Npb8CJpJKAa0QOja9z3lunu+d4LHoEM143TSwLylJSUkXiZqMhlU0GHP7N9vT6mrTeeKo9BV/RjGePLo6iok5l7ouy30vMRtCnc3/FKAm8CpRMB4F+Hrir2O/DvnqeJ6wefSOLxfs2e8CqMQ+k0wVmshlcRW58TgF9RBLKIEf6VNPnufjOVTisB+ueyUCK+rOsW6Kft0N++KJX0DmrUm/tmR6a+dbfFmNv7Q264RlTJly3w/OXpsjQ9sf+htkj7gs3hK/LrvTTSjopYph6q2BLBU1FzZUgHXqgOCEIHlgG4SYzp1X9RXoYIerMYqrwj+pRlyp0a6QgQHicJNdurJ2dKXveZXEGMYvEgeXf/XiwzvE8dVGTtOwb41pz8Lp5jjuCR3UPn3wOdRzbuE0j0wz5z8KBfWOmGOBkFddQGE70lLLXh3/siEP0VWGlpjk/GL5DAynA7R1MzmQ9OzpssPTAaqOwmfVqFliSG3TlboiRx9S3lKbd7jVCzmZS0QgYawDrW+xibGx9T6GuLwa5hGFDsSyV2a/g6JIdnn1/POMzwkbtqkjD7TT+b5Dtm5/OGzfL42RLf3F8Uq5oG31Ic7KaeQ6COm2SmKaXMWez/5OKqy0c43DA2U1UyRwN64h4KjfRvzsgWezhLUVBAfTYoDYddbN7m/148+/YlE=
  matrix:
  - SCC_DOCKER_IMAGE=anthonydenecheau/scc-fluentd:version1.0
script:
- docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
- mvn clean package docker:build
- docker push $SCC_DOCKER_IMAGE
  